### ISSUE TITLE
Missing keybinds from some mods?

### ISSUE THREAD

**Issue by 2bithacker** [tiffit/BindTweaker#1]
I was looking into creating a keybind script to handle armor mode / abilities from Mekanism and Constructs Armory, and started off just dumping the list of keybinds. It worked, but it seems like the log is missing a lot of keybinds, particularly the Mekanism binds.

Script:
```
if(mod.bt.Util.isClient()){
    # Print existing keybinds to the log for reference
    mod.bt.Manager.printBinds();
}
```

crafttweaker.log:
https://gist.github.com/2bithacker/df795ec5db16a3fcaef972069fbfc52b

Not sure if I'm just missing something, or if Mekanism is installing its binds after BT/CT initializes.

**Comment by tiffit** [comment]
Hmm. My guess is that Mekanism adds it’s binds after the script is run aswell. Will look into.
